---
name: Sample KrakenD configuration
version: 1
default_max_rate: 0
client_max_rate: 0
throttling_header: ''
timeout: 3000ms
cache_ttl: 300s
host:
- http://127.0.0.1:8080
- http://localhost:8080
endpoints:
- endpoint: "/xpath"
  method: GET
  timeout: 3000ms
  processors:
    formatter:
      engine: mxj
    indexer:
      engine: bleve
  backend:
  - host:
    - https://api.github.com
    processors:
      formatter:
        engine: mxj
      indexer:
        engine: bleve
    url_pattern: "/"
    whitelist:
    - authorizations_url
    - code_search_url
- endpoint: "/github"
  method: GET
  timeout: 3000ms
  processors:
    formatter:
      engine: mxj
    indexer:
      engine: bleve
  backend:
  - host:
    - https://api.github.com
    processors:
      formatter:
        engine: mxj
      indexer:
        engine: bleve
    url_pattern: "/"
    whitelist:
    - authorizations_url
    - code_search_url
- endpoint: "/apis/specs"
  method: GET
  timeout: 3000ms
  processors:
    formatter:
      engine: mxj
    indexer:
      engine: bleve
  header:
  - 'User-Agent: {USER_AGENT}'
  backend:
  - host:
    - https://api.apis.guru
    encoding: json
    method: GET
    timeout: 3000ms
    url_pattern: "/v2/list.json"
    paths:
    - path: preferred
      rename: default_version
    - path: x-preferred
      rename: use_default_version
    - path: info.title
      rename: description
    - path: info.version
      rename: version
    - path: info.x-apisguru-categories
      rename: topics
    - path: updated
      rename: updated
    - path: swaggerUrl
      rename: swagger_url_json
    - path: swaggerYamlUrl
      rename: swagger_url_yaml
    - path: info.x-origin
      rename: reference_source
    - path: info.x-providerName
      rename: provider
    processors:
      formatter:
        engine: mxj
      indexer:
        engine: bleve
    indexes:
      disabled: false
      mappings:
      - map: ''
        type: ''
    entities:
      disabled: false
      mappings:
      - map: ''
        type: ''
        key: 
    whitelist:
    - preferred
    - added
    - updated
    - swagger_url_json
    - swagger_url_yaml
    - info
    - version
    - default_version
    - topics
    header:
    - 'Accept: application/vnd.github.mercy-preview+json'
    - 'Authentication: token {GITHUB_TOKEN}'
    - 'User-Agent: {USER_AGENT}'
    group: specs
  - host:
    - https://api.apis.guru
    encoding: json
    method: GET
    timeout: 3000ms
    url_pattern: "/v2/metrics.json"
    processors:
      formatter:
        engine: mxj
      indexer:
        engine: bleve
    paths:
    - path: numAPIs
      rename: apis
    - path: numEndpoints
      rename: endpoints
    - path: numSpecs
      rename: specs
    whitelist:
    - apis
    - endpoints
    - specs
    group: metrics
- endpoint: "/search/{q}"
  method: GET
  timeout: 3000ms
  processors:
    formatter:
      engine: mxj
    indexer:
      engine: bleve
  header:
  - 'User-Agent: {USER_AGENT}'
  taskq:
  - id:
      host_slug: 
    order: 1
    type: series
  - id:
      host_slug: 
    order: 2
    type: parallel
  - id:
      host_slug: 
    order: 3
    type: mixed
    map: 
  backend:
  - host:
    - https://api.github.com
    encoding: json
    method: GET
    timeout: 3000ms
    url_pattern: "/search/repositories"
    processors:
      formatter:
        engine: mxj
      indexer:
        engine: bleve
    query_strings:
      q: "{q}"
      sort: stars
      order: desc
      page: 1
      per_page: 3
    holders:
    - key: ratelimit-limit
      location: header
      match: X-RateLimit-Limit
    - key: ratelimit-reset
      location: header
      match: X-Ratelimit-Reset
    - key: ratelimit-remaining
      location: header
      match: X-RateLimit-Remaining
    - key: page-next
      location: header
      match: "?page=(0-9+)>; rel=\"next\""
    - key: page-last
      location: header
      match: "?page=(0-9+)>; rel=\"last\""
    paths:
    - path: items.name
      target: items
      rename: results
    whitelist:
    - items
    - results
    - total_count
    - incomplete_results
    header:
    - 'Accept: application/vnd.github.mercy-preview+json'
    - 'Authentication: token {GITHUB_TOKEN}'
    - 'User-Agent: {USER_AGENT}'
    group: repositories