---
name: Sample KrakenD configuration
version: 1
host:
- http://127.0.0.1:8080
- http://localhost:8080
endpoints:
- endpoint: "/search/{q}"
  method: GET
  timeout: 3000
  cache_ttl: 3600
  header:
  - 'User-Agent: {USER_AGENT}'
  backend:
  - host:
    - https://api.github.com
    url_pattern: "/search/repositories"
    query_strings:
      q: "{q}"
      sort: stars
      order: desc
      page: 1
      per_page: 100
    headers:
    - 'Accept: application/vnd.github.mercy-preview+json'
    - 'Authentication: token {GITHUB_TOKEN}'
    - 'User-Agent: {USER_AGENT}'
    whitelist:
    - full_name
    - name
    - html_url
    - description
    - created_at
    - updated_at
    - pushed_at
    - language
    - stargazers_count
    - watchers_count
    mapping:
      homepage: website
oauth:
  disable: true
cache_ttl: 30m
timeout: 5s
