basePath: /api/11
consumes.length: 1
consumes[0]: application/json
definitions.SentimentEntity.properties.score.description: cosine distance
definitions.SentimentEntity.properties.score.format: double
definitions.SentimentEntity.properties.score.type: number
definitions.SentimentEntity.properties.sentiment.description: sentiment
definitions.SentimentEntity.properties.sentiment.type: string
definitions.SentimentEntity.required.length: 2
definitions.SentimentEntity.required[0]: score
definitions.SentimentEntity.required[1]: sentiment
definitions.SentimentEntity.type: object
definitions.SentimentResponseEntity.properties.endTime.description: End date
definitions.SentimentResponseEntity.properties.endTime.type: string
definitions.SentimentResponseEntity.properties.log.description: Log message
definitions.SentimentResponseEntity.properties.log.type: string
definitions.SentimentResponseEntity.properties.predict.$ref: '#/definitions/SentimentEntity'
definitions.SentimentResponseEntity.properties.predict.description: 'Output: prediction'
definitions.SentimentResponseEntity.properties.processTime.description: Process time
  [millisecond]
definitions.SentimentResponseEntity.properties.processTime.type: string
definitions.SentimentResponseEntity.properties.sentiments.description: 'Output: sentiments'
definitions.SentimentResponseEntity.properties.sentiments.items.$ref: '#/definitions/SentimentEntity'
definitions.SentimentResponseEntity.properties.sentiments.type: array
definitions.SentimentResponseEntity.properties.startTime.description: Start date
definitions.SentimentResponseEntity.properties.startTime.type: string
definitions.SentimentResponseEntity.properties.text.description: 'Input: text'
definitions.SentimentResponseEntity.properties.text.type: string
definitions.SentimentResponseEntity.required.length: 7
definitions.SentimentResponseEntity.required[0]: endTime
definitions.SentimentResponseEntity.required[1]: log
definitions.SentimentResponseEntity.required[2]: predict
definitions.SentimentResponseEntity.required[3]: processTime
definitions.SentimentResponseEntity.required[4]: sentiments
definitions.SentimentResponseEntity.required[5]: startTime
definitions.SentimentResponseEntity.required[6]: text
definitions.SentimentResponseEntity.type: object
host: api.apitore.com
info.description: Japanese sentiment analyzer.<BR />[Endpoint] https://api.apitore.com/api/11
info.title: Sentiment APIs
info.version: 1.0.6
info.x-apisguru-categories.length: 2
info.x-apisguru-categories[0]: developer_tools
info.x-apisguru-categories[1]: text
info.x-logo.url: https://api.apis.guru/v2/cache/logo/https_apitore.com_img_apis_11.jpg
info.x-origin.length: 1
info.x-origin[0].format: swagger
info.x-origin[0].url: https://api.apitore.com/json/11
info.x-origin[0].version: "2.0"
info.x-preferred: false
info.x-providerName: apitore.com
info.x-serviceName: sentimentApis
paths./sentiment/predict.get.description: 'Sentiment Analysis, last update at 2017-5-12.<BR
  />Response<BR />&nbsp; Github: <a href="https://github.com/keigohtr/apitore-response-parent/tree/master/word2vec-response">word2vec-response</a><BR
  />&nbsp; Class: com.apitore.banana.response.sentiment.SentimentResponseEntity<BR
  />'
paths./sentiment/predict.get.operationId: predictUsingGET
paths./sentiment/predict.get.parameters.length: 2
paths./sentiment/predict.get.parameters[0].description: Access Token
paths./sentiment/predict.get.parameters[0].in: query
paths./sentiment/predict.get.parameters[0].name: access_token
paths./sentiment/predict.get.parameters[0].required: true
paths./sentiment/predict.get.parameters[0].type: string
paths./sentiment/predict.get.parameters[1].description: text
paths./sentiment/predict.get.parameters[1].in: query
paths./sentiment/predict.get.parameters[1].name: text
paths./sentiment/predict.get.parameters[1].required: true
paths./sentiment/predict.get.parameters[1].type: string
paths./sentiment/predict.get.responses.200.description: OK
paths./sentiment/predict.get.responses.200.schema.$ref: '#/definitions/SentimentResponseEntity'
paths./sentiment/predict.get.responses.401.description: Unauthorized
paths./sentiment/predict.get.responses.403.description: Forbidden
paths./sentiment/predict.get.responses.404.description: Not Found
paths./sentiment/predict.get.summary: Sentiment predict
paths./sentiment/predict.get.tags.length: 1
paths./sentiment/predict.get.tags[0]: sentiment-controller
produces.length: 1
produces[0]: application/json
schemes.length: 1
schemes[0]: https
swagger: "2.0"
tags.length: 1
tags[0].description: Sentiment Controller
tags[0].name: sentiment-controller
